ServiceAuto/ServiceAuto/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceAuto.Models;
using ServiceAuto.Services;
using ServiceAuto.Services.Interfaces;

namespace ServiceAuto.Controllers
{
    //CarsController
    public class CarsController : Controller
    {
        private readonly CarService carService;
        private readonly ServiceService serviceService;
        private readonly ExpenseReportService expenseReportService;

        public CarsController(CarService cService, ServiceService serService, ExpenseReportService expReportService)
        {
            carService = cService;
            serviceService = serService;
            expenseReportService = expReportService;
        }

        // GET: Cars
        public ActionResult Index()
        {
            var cars = carService.GetCars();
            return View(cars);
        }

        // GET: Cars/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = carService.GetCar(id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,CarBrand,CarModel,CarProductYear,CarPrice,CarPhoto")] Car car)
        {
            if (ModelState.IsValid)
            {
                carService.AddCar(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = carService.GetCar(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Id,CarBrand,CarModel,CarProductYear,CarPrice,CarPhoto")] Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    carService.UpdateCar(car);
                    return RedirectToAction(nameof(Index));
                }
                catch 
                {
                    return View(car);
                }
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var car = carService.GetCar(id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (carService.GetCars() == null)
            {
                return Problem("Entity set 'ServiceingContext.Cars'  is null.");
            }
            var car = carService.GetCar(id);
            if (car != null)
            {
                carService.DeleteCar(id);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,User")]
        public ActionResult Buy(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = carService.GetCar(id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [Authorize(Roles = "Admin,User")]
        [HttpPost, ActionName("Buy")]
        [ValidateAntiForgeryToken]
        public ActionResult BuyConfirmed(int id)
        {
            if (carService.GetCars() == null)
            {
                return Problem("Entity set 'ServiceingContext.Cars'  is null.");
            }
            var car = carService.GetCar(id);
            if (car != null)
            {
                var service = serviceService.GetServiceByName("Central");
                if (service == null)
                {
                    return NotFound();
                }

                var expenseReport = expenseReportService.GetExpenseReportByServiceId(service.Id);
                if (expenseReport == null)
                {
                    return NotFound();
                }

                expenseReport.ExpenseReportIncome += car.CarPrice;
                expenseReportService.UpdateExpenseReport(expenseReport);
                expenseReportService.UpdateExpenseReportProfit(expenseReport);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ServiceAuto/ServiceAuto/Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceAuto.Models;
using ServiceAuto.Services;
using System.Diagnostics;

namespace ServiceAuto.Controllers
{
    //ContactsController
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;
        private readonly ContactService contactService;

        public ContactController(ILogger<ContactController> logger, ContactService conService)
        {
            contactService = conService;
            _logger = logger;
        }
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles ="Admin")]
        public ActionResult List()
        {
            var contacts = contactService.GetContacts();   
            return View(contacts);
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = contactService.GetContact(id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,ContactFirstName,ContactLastName,ContactEmail,ContactSubject,ContactContext")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                contactService.AddContact(contact);
                return RedirectToAction(nameof(Confirm));
            }
            return View(contact);
        }

        public ActionResult Confirm()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = contactService.GetContact(id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (contactService.GetContacts() == null)
            {
                return Problem("Entity set 'ServiceingContext.Cars'  is null.");
            }
            var contact = contactService.GetContact(id);
            if (contact != null)
            {
                contactService.DeleteContact(id);
            }

            return RedirectToAction(nameof(List));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ServiceAuto/ServiceAuto/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceAuto.Models;
using System.Diagnostics;

namespace ServiceAuto.Controllers
{
    //InfoController
    public class InfoController : Controller
    {
        private readonly ILogger<InfoController> _logger;

        public InfoController(ILogger<InfoController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ServiceAuto/ServiceAuto/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceAuto.Models;
using System.Diagnostics;

namespace ServiceAuto.Controllers
{
    //NewsController
    public class NewsController : Controller
    {
        private readonly ILogger<NewsController> _logger;

        public NewsController(ILogger<NewsController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ServiceAuto/ServiceAuto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ServiceAuto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Home.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Info.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/News.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Contact.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ProgramareService.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ServiceAuto.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="header">
        <img src="/img/WW_Logo.png" class="center" alt="WW logo" height="100" width="75">
        <h1 class="headpos">Volkswagen Service</h1>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @* <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">ServiceAuto</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between text-white">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="News" asp-action="Index">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Info" asp-action="Index">Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="CarParts" asp-action="Index">Piese Auto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Cars" asp-action="Index">Masini</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Services" asp-action="Index">Service List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ProgramareServices" asp-action="Index">Programare Service</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a href="https://www.facebook.com/VolkswagenRomania/"><img src="/img/Facebook.png" id="f1" alt="Facebook" height="50px" width="50px"></a>
            <a href="https://www.instagram.com/volkswagen_romania/"><img src="/img/Instagram.png" id="f2" alt="Instagram" height="50px" width="50px"></a>
            <a href="https://www.youtube.com/user/VolkswagenRomania"><img src="/img/Youtube.png" id="f3" alt="Youtube" height="50px" width="50px"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>