ServiceAuto/ServiceAuto/Models/Service.cs
namespace ServiceAuto.Models
{
    public class Service : ModelEntity
    {
      
        public string? ServiceName { get; set; }
        public string? ServiceDescription { get; set;}
        public string? ServiceAddress1 { get; set;}
        public string? ServiceCity { get; set;}
        public string? ServiceState { get; set;}

        public ICollection<Employee>? Employees { get; set;}
        public ExpenseReport? ExpenseReport { get; set;}
    }
}

ServiceAuto/ServiceAuto/Controllers/EmployeeAddressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceAuto.Models;
using ServiceAuto.Services;
using ServiceAuto.Services.Interfaces;

namespace ServiceAuto.Controllers
{
    //EmployeeAddressesController

    [Authorize(Roles = "Admin")]
    public class EmployeeAddressesController : Controller
    {
        private readonly EmployeeAddressService employeeAddressService;
        private readonly EmployeeService employeeService;

        public EmployeeAddressesController(EmployeeAddressService empAService, EmployeeService empService)
        {
            employeeAddressService = empAService;
            employeeService = empService;
        }

        // GET: EmployeeAddresses
        public ActionResult Index()
        {
            var employeeAddresses = employeeAddressService.GetEmployeeAddresses();
            return View(employeeAddresses);
        }

        // GET: EmployeeAddresses/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeeAddress = employeeAddressService.GetEmployeeAddress(id);
            if (employeeAddress == null)
            {
                return NotFound();
            }

            return View(employeeAddress);
        }

        // GET: EmployeeAddresses/Create
        public ActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(employeeService.GetEmployees(), "Id", "Id");
            return View();
        }

        // POST: EmployeeAddresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("EmployeeAddress1,EmployeeCity,EmployeeState,EmployeeId,Id")] EmployeeAddress employeeAddress)
        {
            if (ModelState.IsValid)
            {
                employeeAddressService.AddEmployeeAddress(employeeAddress);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(employeeService.GetEmployees(), "Id", "Id", employeeAddress.EmployeeId);
            return View(employeeAddress);
        }

        // GET: EmployeeAddresses/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeeAddress = employeeAddressService.GetEmployeeAddress(id);
            if (employeeAddress == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(employeeService.GetEmployees(), "Id", "Id", employeeAddress.EmployeeId);
            return View(employeeAddress);
        }

        // POST: EmployeeAddresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("EmployeeAddress1,EmployeeCity,EmployeeState,EmployeeId,Id")] EmployeeAddress employeeAddress)
        {
            if (id != employeeAddress.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    employeeAddressService.UpdateEmployeeAddress(employeeAddress);
                    return RedirectToAction(nameof(Index));
                }
                catch 
                {
                    return View(employeeAddress);
                }             
            }
            ViewData["EmployeeId"] = new SelectList(employeeService.GetEmployees(), "Id", "Id", employeeAddress.EmployeeId);
            return View(employeeAddress);
        }

        // GET: EmployeeAddresses/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeeAddress = employeeAddressService.GetEmployeeAddress(id);
            if (employeeAddress == null)
            {
                return NotFound();
            }

            return View(employeeAddress);
        }

        // POST: EmployeeAddresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (employeeAddressService.GetEmployeeAddresses() == null)
            {
                return Problem("Entity set 'ServiceingContext.EmployeeAddresses'  is null.");
            }
            var employeeAddress = employeeAddressService.GetEmployeeAddress(id);
            if (employeeAddress != null)
            {
                employeeAddressService.DeleteEmployeeAddress(id);
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

ServiceAuto/ServiceAuto/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceAuto.Models;
using ServiceAuto.Services;

namespace ServiceAuto.Controllers
{
    //EmployeesController

    [Authorize(Roles = "Admin")]
    public class EmployeesController : Controller
    {
        private readonly EmployeeService employeeService;
        private readonly ServiceService serviceService;
        private readonly ExpenseReportService expenseReportService;

        public EmployeesController(EmployeeService empService, ServiceService serService, ExpenseReportService expReportService)
        {
            employeeService = empService;
            serviceService = serService;
            expenseReportService = expReportService;
        }

        // GET: Employees
        public ActionResult Index()
        {
            var employees = employeeService.GetEmployees();
            return View(employees);
        }

        // GET: Employees/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeService.GetEmployee(id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewData["ServiceName"] = new SelectList(serviceService.GetServices(), "ServiceName", "ServiceName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,EmployeeName,EmployeeAge,EmployeeSalary")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employeeService.AddEmployee(employee);
                var service = serviceService.GetServiceByName("Central");
                var expenseReport = expenseReportService.GetExpenseReportByServiceId(service.Id);
                if(service != null && expenseReport != null && employee.EmployeeSalary != null)
                {
                    expenseReport.ExpenseReportExpense += employee.EmployeeSalary;
                    expenseReportService.UpdateExpenseReport(expenseReport);
                    expenseReportService.UpdateExpenseReportProfit(expenseReport);
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ServiceName"] = new SelectList(serviceService.GetServices(), "ServiceName", "ServiceName", employee.EmployeeServiceName);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeService.GetEmployee(id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["ServiceName"] = new SelectList(serviceService.GetServices(), "ServiceName", "ServiceName", employee.EmployeeServiceName);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("Id,EmployeeName,EmployeeAge,EmployeeSalary")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    employeeService.UpdateEmployee(employee);
                    var service = serviceService.GetServiceByName("Central");
                    var expenseReport = expenseReportService.GetExpenseReportByServiceId(service.Id);
                    if (service != null && expenseReport != null && employee.EmployeeSalary != null)
                    {
                        expenseReport.ExpenseReportExpense += employee.EmployeeSalary;
                        expenseReportService.UpdateExpenseReport(expenseReport);
                        expenseReportService.UpdateExpenseReportProfit(expenseReport);
                    }
                    return RedirectToAction(nameof(Index));
                }
                catch 
                {
                    return View(employee);
                }             
            }
            ViewData["ServiceName"] = new SelectList(serviceService.GetServices(), "ServiceName", "ServiceName", employee.EmployeeServiceName);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeService.GetEmployee(id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (employeeService.GetEmployees() == null)
            {
                return Problem("Entity set 'ServiceingContext.Employees'  is null.");
            }
            var employee = employeeService.GetEmployee(id);
            if (employee != null)
            {
                employeeService.DeleteEmployee(id);
                var service = serviceService.GetServiceByName("Central");
                var expenseReport = expenseReportService.GetExpenseReportByServiceId(service.Id);
                if (service != null && expenseReport != null && employee.EmployeeSalary != null)
                {
                    expenseReport.ExpenseReportExpense -= employee.EmployeeSalary;
                    expenseReportService.UpdateExpenseReport(expenseReport);
                    expenseReportService.UpdateExpenseReportProfit(expenseReport);
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ServiceAuto/ServiceAuto/Controllers/ExpenseReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceAuto.Models;
using ServiceAuto.Services;
using SQLitePCL;

namespace ServiceAuto.Controllers
{
    //ExpenseReportsController

    [Authorize(Roles = "Admin")]
    public class ExpenseReportsController : Controller
    {
      
        private readonly ExpenseReportService expenseReportService;
        private readonly ServiceService serviceService;

        public ExpenseReportsController(ExpenseReportService expReportService, ServiceService serService)
        {
            expenseReportService = expReportService;
            serviceService = serService;
        }

        // GET: ExpenseReports
        public ActionResult Index()
        {
            var expenseReports = expenseReportService.GetExpenseReports();    
            return View(expenseReports);
        }

        // GET: ExpenseReports/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenseReport = expenseReportService.GetExpenseReport(id);
            if (expenseReport == null)
            {
                return NotFound();
            }

            return View(expenseReport);
        }

        // GET: ExpenseReports/Create
        public ActionResult Create()
        {
            ViewData["ServiceId"] = new SelectList(serviceService.GetServices(), "Id", "Id");
            return View();
        }

        // POST: ExpenseReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("ExpenseReportExpense,ExpenseReportIncome,ExpenseReportProfit,ServiceId,Id")] ExpenseReport expenseReport)
        {
            if (ModelState.IsValid)
            {
                expenseReportService.AddExpenseReport(expenseReport);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ServiceId"] = new SelectList(serviceService.GetServices(), "Id", "Id", expenseReport.ServiceId);
            return View(expenseReport);
        }

        // GET: ExpenseReports/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenseReport = expenseReportService.GetExpenseReport(id);
            if (expenseReport == null)
            {
                return NotFound();
            }
            ViewData["ServiceId"] = new SelectList(serviceService.GetServices(), "Id", "Id", expenseReport.ServiceId);
            return View(expenseReport);
        }

        // POST: ExpenseReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("ExpenseReportExpense,ExpenseReportIncome,ExpenseReportProfit,ServiceId,Id")] ExpenseReport expenseReport)
        {
            if (id != expenseReport.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    expenseReportService.UpdateExpenseReport(expenseReport);
                    return RedirectToAction(nameof(Index));
                }
                catch 
                {
                    return View(expenseReport);
                }            
            }
            ViewData["ServiceId"] = new SelectList(serviceService.GetServices(), "Id", "Id", expenseReport.ServiceId);
            return View(expenseReport);
        }

        // GET: ExpenseReports/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenseReport = expenseReportService.GetExpenseReport(id);
            if (expenseReport == null)
            {
                return NotFound();
            }

            return View(expenseReport);
        }

        // POST: ExpenseReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (expenseReportService.GetExpenseReports() == null)
            {
                return Problem("Entity set 'ServiceingContext.ExpenseReports'  is null.");
            }
            var expenseReport = expenseReportService.GetExpenseReport(id);
            if (expenseReport != null)
            {
                expenseReportService.DeleteExpenseReport(id);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ServiceAuto/ServiceAuto/Views/Services/Create.cshtml
@model ServiceAuto.Models.Service

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceDescription" class="control-label"></label>
                <input asp-for="ServiceDescription" class="form-control" />
                <span asp-validation-for="ServiceDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceAddress1" class="control-label"></label>
                <input asp-for="ServiceAddress1" class="form-control" />
                <span asp-validation-for="ServiceAddress1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceCity" class="control-label"></label>
                <input asp-for="ServiceCity" class="form-control" />
                <span asp-validation-for="ServiceCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceState" class="control-label"></label>
                <input asp-for="ServiceState" class="form-control" />
                <span asp-validation-for="ServiceState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ServiceAuto/ServiceAuto/Views/Services/Delete.cshtml
@model ServiceAuto.Models.Service

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceAddress1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceAddress1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceState)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ServiceAuto/ServiceAuto/Views/Services/Details.cshtml
@model ServiceAuto.Models.Service

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceAddress1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceAddress1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceState)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ServiceAuto/ServiceAuto/Views/Services/Edit.cshtml
@model ServiceAuto.Models.Service

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceDescription" class="control-label"></label>
                <input asp-for="ServiceDescription" class="form-control" />
                <span asp-validation-for="ServiceDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceAddress1" class="control-label"></label>
                <input asp-for="ServiceAddress1" class="form-control" />
                <span asp-validation-for="ServiceAddress1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceCity" class="control-label"></label>
                <input asp-for="ServiceCity" class="form-control" />
                <span asp-validation-for="ServiceCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceState" class="control-label"></label>
                <input asp-for="ServiceState" class="form-control" />
                <span asp-validation-for="ServiceState" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ServiceAuto/ServiceAuto/Views/Services/Index.cshtml
@model IEnumerable<ServiceAuto.Models.Service>

@{
    ViewData["Title"] = "Index";
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
        <div class="container-fluid">
            @* <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">ServiceAuto</a>*@
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between text-white">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="EmployeeAddresses" asp-action="Index">Address List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="ExpenseReports" asp-action="Index">Expense Report</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<h1>Services</h1>

<p>
    <a asp-action="Create">Add New Service</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ServiceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceAddress1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceState)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceAddress1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceState)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>